const C_STATUS_HTTP = {
  OK: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
} as const;

const C_REASON_STATUS_HTTP = {
  [C_STATUS_HTTP.OK]: "OK",
  [C_STATUS_HTTP.BAD_REQUEST]: "Bad Request",
  [C_STATUS_HTTP.NOT_FOUND]: "Not Found",
  [C_STATUS_HTTP.METHOD_NOT_ALLOWED]: "Method Not Allowed",
  [C_STATUS_HTTP.INTERNAL_SERVER_ERROR]: "Internal Server Error",
} as Record<number, string>;

export { C_STATUS_HTTP, C_REASON_STATUS_HTTP };
